server:
  port: 80

spring:
  application:
   name: SangsuShop
   
  devtools:
    livereload:
      enabled: true # 화면 갱신
    restart:
      enabled: true # 재시작
  
  thymeleaf:  # 엣날껄 물지 않게 해줌, jpa처럼 엣날거 물어서 클린할 필요없음
    cache: false # 캐쉬 안함


  # MySql 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_a
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update  #update / create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  security:
    user:
      name: test
      password: 1234


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


